# PLUGINS
# ===
# See config/plugins/all.vim for plugin mappings and config/plugins/*.vim

# Startup
# -------
- repo: itchyny/vim-gitbranch
  if: 0
- repo: itchyny/vim-parenmatch
  if: 0
- repo: thinca/vim-localrc
  if: 0
- repo: romainl/vim-cool
  if: 0
- { repo: wellle/visual-split.vim, if: 0 }
- repo: rafi/awesome-vim-colorschemes
  merged: 0
  hook_add: let g:onedark_terminal_italics=1

# Lazy Loading
# ==========================================

- repo: lervag/vimtex
  on_ft: tex

- repo: pearofducks/ansible-vim
  if: 0

# ==========================================
# Commands
# --------

- { repo: Shougo/vinarise.vim, if: 0}
  # use Shougo/deorise.nvim

- { repo: guns/xterm-color-table.vim, if: 0}

- { repo: cocopon/colorswatch.vim, if: 0}

- repo: t9md/vim-choosewin
  if: 0

# ==========================================
# Language & Codes
# ---------

# loaded only on demand
- repo: sheerun/vim-polyglot
  hook_add: let g:polyglot_disabled = ['css', 'latex']

- repo: sbdchd/neoformat
  hook_source: source $VIM_PATH/config/plugins/neoformat.vim
  on_cmd: Neoformat

# Golang related
- repo: fatih/vim-go
  if: has('nvim-0.3.2') || has('patch-8.0.1453')
  on_ft: [ go, gomod ]
  hook_add: |
    let g:go_gopls_enabled = 1
    let g:go_code_completion_enabled = 0
    let g:go_doc_keywordprg_enabled = 1
    let g:go_def_mapping_enabled = 0
    let g:go_mod_fmt_autosave = 0
    let g:go_echo_go_info = 0
    let g:go_list_type = "quickfix"
    let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
    let g:go_metalinter_autosave_enabled = ['vet', 'golint']
    let g:go_metalinter_autosave = 1
    let g:go_decls_includes = "func,type"
    let g:go_auto_type_info = 1
    let g:go_highlight_array_whitespace_error = 1
    let g:go_highlight_chan_whitespace_error = 1
    let g:go_highlight_space_tab_error = 1
    let g:go_highlight_trailing_whitespace_error = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_extra_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_format_strings = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_function_parameters = 1
    let g:go_highlight_types = 1
    let g:go_highlight_generate_tags = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_string_spellcheck = 0
    let g:go_highlight_variable_declarations = 1
    let g:go_highlight_variable_assignments = 0

- repo: dense-analysis/ale
  on_event: FileType
  hook_add: |
    let g:ale_disable_lsp = 0
    let g:ale_echo_delay = 100
    let g:ale_lint_delay = 1000
    let g:ale_echo_msg_format = '%linter%: %code: %%s [%severity%]'
    let g:ale_history_enabled = 0
    let g:ale_sign_error = '✖'
    let g:ale_sign_warning = 'ⁱ'
    let g:ale_maximum_file_size = 500000
    let g:ale_linters = {
            \ 'go': ['gobuild'],
            \ 'cpp': ['clangd', 'ccls', 'clangcheck', 'clangtidy', 'cppcheck']
            \ }
    let g:ale_fixers = {
    \   '*': ['remove_trailing_lines', 'trim_whitespace'],
    \   'javascript': ['eslint'],
    \   'cpp': ['clangtidy']
    \}
    let g:ale_fix_on_save = 1

- repo: mattn/vim-lsp-settings
  depends: vim-lsp
  merged: 0
  hook_add: |
    let g:lsp_settings = {
    \   'texlab': {
    \     'cmd': ['texlab'],
    \     'whitelist': ['tex', 'plaintex', 'bib'],
    \   }
    \ }

- repo: prabirshrestha/asyncomplete-tags.vim
  if: executable('ctags')
  depends: asyncomplete.vim
  hook_source: |
    autocmd User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#tags#get_source_options({
      \ 'name': 'tags',
      \ 'whitelist': ['*'],
      \ 'blacklist': ['go', 'python', 'vim', 'denite-filter', 'clap_input', 'tex'],
      \ 'completor': function('asyncomplete#sources#tags#completor'),
      \ 'config': { 'max_file_size': 5000000 },
      \ }))

# ==========================================
# Interface
# ---------

- { repo: haya14busa/vim-edgemotion, if: 0 }
- { repo: t9md/vim-quickhl, if: 0 }

- repo: mhinz/vim-startify
  hook_source: source $VIM_PATH/config/plugins/startify.vim

- repo: itchyny/lightline.vim
  hook_add: |
    let g:lightline = {
      \ 'colorscheme': 'onedark',
      \ }

- repo: luochen1990/rainbow
  on_event: VimEnter
  hook_add: let g:rainbow_active = 1


# ==========================================
# Completion and code analysis
# ----------


# ==========================================
# Operators
# ---------
- repo: kana/vim-operator-user  # only autoload functions, lazy by nature
  if: 0

- repo: kana/vim-operator-replace
  if: 0

- repo: machakann/vim-sandwich
  if: 0

# alternative for vim-sandwich
- repo: tpope/vim-surround
  on_event: VimEnter

# ==========================================
# Text objects
# ------------
- repo: kana/vim-textobj-user  # only autoload functions, lazy by nature
- { repo: terryma/vim-expand-region, if: 0 }

- repo: osyo-manga/vim-textobj-multiblock
  if: 0

- repo: kana/vim-textobj-function
  if: 0

- repo: simnalamburt/vim-tiny-ime
  build: 'bash ./build'

#  vim: set ts=2 sw=2 tw=80 et :
